# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=10, verbose_name='编号')),
                ('Name', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=10)),
                ('Price', models.CharField(max_length=20)),
                ('Donater', models.CharField(max_length=50)),
                ('Avaliable', models.BooleanField()),
                ('LastCheckTime', models.DateField(blank=True, null=True)),
                ('Remark', models.TextField(blank=True)),
            ],
        ),
    ]
