# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=50)),
                ('Types', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Isbn', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('Ordered', models.BooleanField(default=False)),
                ('Keeper', models.TextField(blank=True)),
                ('Keepertel', models.CharField(blank=True, max_length=50, null=True)),
                ('Endtime', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher'),
        ),
    ]
